# Generated by Django 4.1.7 on 2023-05-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECG_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('signal_x', models.CharField(max_length=200, null=True)),
                ('signla_y', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
