# Generated by Django 4.1.7 on 2023-06-05 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ECG_feat', '0002_alter_ecg_model_options_remove_ecg_model_signla_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecg_model',
            name='signal_x',
        ),
        migrations.RemoveField(
            model_name='ecg_model',
            name='signal_y',
        ),
        migrations.AddField(
            model_name='ecg_model',
            name='amp',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecg_model',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
