# Generated by Django 4.1.7 on 2023-06-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECG_feat', '0003_remove_ecg_model_signal_x_remove_ecg_model_signal_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECG_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amp', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
