# Generated by Django 4.2.2 on 2024-11-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECG_feat', '0006_remove_customuser_phone_number_customuser_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='key',
        ),
    ]
