# Generated by Django 4.2.2 on 2024-11-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECG_feat', '0007_delete_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
