# Generated by Django 4.2.2 on 2024-12-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECG_feat', '0008_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='vcg_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('amp_1', models.FloatField()),
                ('amp_2', models.FloatField()),
                ('amp_3', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
