# Generated by Django 5.1.4 on 2025-01-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECG_feat', '0010_vcg_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcg_model',
            name='pred',
            field=models.FloatField(default=0.0),
        ),
    ]
